server:
  port: 8080
##  context-path: /springboot
### 数据库配置
spring:
    datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://119.23.74.63:3306/springboot
      username: restart1025
      password: G101225
      type: com.zaxxer.hikari.HikariDataSource
### spring-boot 不推荐JSP，想使用JSP需要配置application.properties
    mvc:
      view:
        prefix: /WEB-INF/view/
        suffix: .jsp
### logback
logging:
  level: warn
  path: d:/restart1025/log
### mybatis
mybatis:
  type-aliases-package: com.restart1025.springbootmybatis.entity
  mapper-locations: classpath*:**/*Mapper.xml
