### active properties
spring:
    profiles:
      active: dev
### 定义静态资源的映射
#### 默认值为 /** 只可定义一个，目前不支持多个逗号分割的方式。
#### spring.mvc.static-path-pattern=
#### 默认值为 classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/
#### spring.resources.static-locations=这里设置要指向的路径，多个使用英文逗号隔开